LogLevel warn
# Listen on all interfaces.
Listen *:631
# Used by lpadmin in entrypoint.
Listen /run/cups/cups.sock
# Allow access from any host.
ServerAlias *

# Don't require auth, since this is a devcontainer.
<Location />
  Order allow,deny
  Allow all
</Location>
