concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/projects/events-cash-register:ci@sha256:ba2179fddf94601722420638e57c371423a337cb55c3e41360a985d4648a14b5
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Checks with static tools
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run types and syntax check
        run: |
          pnpm run -r --no-sort --aggregate-output setup
          pnpm run -r --aggregate-output check

name: check-syntax.yaml

"on":
  pull_request:
    branches:
      - main
