concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/projects/events-cash-register:ci
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Check that project builds
    runs-on: srv-0-nbg-hetz
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Copy .env.example to .env
        run: cp .env.example .env
      - name: Build the website
        run: pnpm run build

name: check-build.yaml

"on":
  pull_request:
    branches:
      - main
