concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/projects/events-cash-register:ci@sha256:38f67817cee277edb2384497a8df56e2416ab2810496a3939d4d1393ee27988c
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
        - forgejo-runner-cache-projects-events-cash-register-turbo:/cache/turbo
    env:
      TURBO_CACHE_DIR: /cache/turbo
    name: Checks with linters
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run linter
        run: turbo run lint:check

name: check-linter.yaml

"on":
  pull_request:
    branches:
      - main
