concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/projects/events-cash-register:ci@sha256:1d3cacfd349d2267376a691eb14b2562be6af5930d473c44f5609c526806399c
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Check that project builds
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Build the website
        run: |
          pnpm run -r --no-sort --aggregate-output setup
          pnpm run -r --aggregate-output build

name: check-build.yaml

"on":
  pull_request:
    branches:
      - main
