jobs:
  respond:
    container:
      image: git.zarantonello.dev/projects/events-cash-register-ci:v2026.09.20.1@sha256:fcf943ffdf3f0394022c0f6bde23c9e7497a9cfe481c253731e88e337a829db9
      # The composite action in action.yaml can save the binary to speed up
      # subsequent runs.
      volumes:
        - forgejo-runner-cache-forgejo-agent:/cache/forgejo-agent
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: LLM Bot response generation
    runs-on: srv-home
    steps:
      - name: Configure pi
        run: |
          mkdir -p $HOME/.pi/agent/
          echo '{"providers":{"llama-server":{"baseUrl":"http://llama.zarantonello.dev/v1","api":"openai-completions","apiKey":"llama","models":[{"id":"Qwen3.6-35B-A3B","contextWindow":65536}]}}}' > $HOME/.pi/agent/models.json
      - name: Generate response
        uses: https://git.zarantonello.dev/projects/forgejo-agent@14d91db19b461745538001cc5a0ed176ef018aec # v1.11.3
        with:
          auth-token: ${{ secrets.CI_BOT_TOKEN }}
          auth-username: ci-bot
          git-author: CI [bot]
          git-email: ci-bot@git.zarantonello.dev

name: forgejo-agent

"on":
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - review_requested
