jobs:
  respond:
    container:
      image: git.zarantonello.dev/projects/events-cash-register:ci@sha256:2059b63a29a9746bc5b55ba2d1f9db657b8e14e4d07ba617c9e160229edae122
      # The composite action in action.yaml can save the binary to speed up
      # subsequent runs.
      volumes:
        - forgejo-runner-cache-forgejo-agent:/cache/forgejo-agent
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: LLM Bot response generation
    runs-on: srv-0-thi-home
    steps:
      - name: Configure pi
        run: |
          mkdir -p $HOME/.pi/agent/
          echo '{"providers":{"llama-server":{"baseUrl":"http://llama.zarantonello.dev/v1","api":"openai-completions","apiKey":"llama","models":[{"id":"Qwen3.6-35B-A3B","contextWindow":65536}]}}}' > $HOME/.pi/agent/models.json
      - name: Generate response
        uses: https://git.zarantonello.dev/projects/forgejo-agent@cc756e4a0bcc0adb016189404146040826512da7 # v1.7.5
        with:
          auth-token: ${{ secrets.AGENT_TOKEN }}
          auth-username: llm-bot
          git-author: LLM [bot]
          git-email: llm-bot@git.zarantonello.dev

name: forgejo-agent

"on":
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - review_requested
