services:
  cups:
    image: git.zarantonello.dev/projects/events-cash-register-cups:v2026.09.19.1@sha256:377e00029f65ef6e2d1e68ed703c92c2e0209e66dd282ac6e502251abe77b308
    volumes:
      - ../data/receipts:/var/spool/ippeveprinter:z

  workspace:
    entrypoint: sleep infinity
    env_file: ../.env
    image: git.zarantonello.dev/projects/events-cash-register-ci:v2026.09.27.1@sha256:14d2077063d06cf41a6e774491303075b5c983bd7b0db6e9917b6fbc4a3e7a5b
    ports:
      - 5173:5173
      - 4983:4983
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
