services:
  cups:
    image: git.zarantonello.dev/projects/events-cash-register-cups:v2026.01.01.1
    volumes:
      - ../data/receipts:/var/spool/ippeveprinter:z

  workspace:
    entrypoint: sleep infinity
    env_file: ../.env
    image: git.zarantonello.dev/projects/events-cash-register-ci:v2026.08.27.1
    ports:
      - 5173:5173
      - 4983:4983
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
