services:
  cups:
    image: git.zarantonello.dev/projects/events-cash-register:cups@sha256:bd7dfa58a031538489045db2940ec208f5ce2294b644edf5081be149695c70de
    volumes:
      - ../data/receipts:/var/spool/ippeveprinter:z

  workspace:
    entrypoint: sleep infinity
    env_file: ../.env
    image: git.zarantonello.dev/projects/events-cash-register:ci@sha256:a38e577b4d880a33f287d585f778f4ddf0f2b2a199bda023f0eae0e00ef07ddd
    ports:
      - 5173:5173
      - 4983:4983
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
