services:
  # TODO: mock cups server.

  workspace:
    entrypoint: sleep infinity
    env_file: ../.env
    image: git.zarantonello.dev/projects/events-cash-register:ci@sha256:911d0b61b8654cb0eb6ba00c7cef1bb7c9c560cfcfbdc10ef2a914272cfc978c
    # Drizzle studio has problems running inside a docker container. The other
    # solution would be running a reverse proxy, but this is simpler.
    network_mode: host
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
