services:
  # TODO: mock cups server.

  workspace:
    entrypoint: sleep infinity
    env_file: ../.env
    image: git.zarantonello.dev/projects/events-cash-register:ci@sha256:690f9864413e43403f1c39766a7bf4c61e956bf6b9c0c559399461fc135d4fca
    # Drizzle studio has problems running inside a docker container. The other
    # solution would be running a reverse proxy, but this is simpler.
    network_mode: host
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
