services:
  # TODO: mock cups server.

  workspace:
    entrypoint: sleep infinity
    env_file: ../.env
    image: git.zarantonello.dev/projects/events-cash-register:ci@sha256:422ed21e1f2a4a194e3b179c0ac231d7dba88b1da8d77d380f64af5fbed000ca
    # Drizzle studio has problems running inside a docker container. The other
    # solution would be running a reverse proxy, but this is simpler.
    network_mode: host
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
